name: Data Pipeline Workflow

on:
  schedule:
    - cron: '0 0 * * 3'  # Triggers every Wednesday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Feature Pipeline
        run: |
            cd src/pipelines
            python 01_feature_pipeline.py

  retraining_pipeline:
    runs-on: ubuntu-latest
    needs: feature_pipeline
    if: success()  # Only runs if the previous job was successful
    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Retraining Pipeline
        run: |
            cd src/pipelines
            python 02_retraining_pipeline.py

  deployment_pipeline:
    runs-on: ubuntu-latest
    needs: retraining_pipeline
    if: success()  # Only runs if the previous job was successful
    env:
      HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Deployment Pipeline
        run: |
            cd src/pipelines
            python 03_deployment_pipeline.py